apiVersion: v1
data:
  backend.service.port: "8080"
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-20T16:10:35Z"
  name: backend-service-port
  namespace: frontend
  resourceVersion: "4931282"
  uid: 44162408-855e-4603-81b2-0981f5487b0b
